# Project language
language: php

# Allows use of container-based infrastructure
sudo: false

# Services

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.1


# Define an environment variable
env:
  - SYMFONY_VERSION="4.1.*"
  #- SYMFONY_VERSION="4.1.*" DB=mysql

# Update composer
before-install:
  - composer self-update
  - cp .env.dist .env

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install

# Run script
script:
  - bin/phpunit

# After a build, send email notification with the build results
notifications:
  email: bitblitter@gmail.com
